server:
  port: 8085

spring:
  application:
    name: combat-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: combat_db

# Service auth pour validation token
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

# Service monstre
monster:
  service:
    url: ${MONSTER_SERVICE_URL:http://localhost:8083}
