server:
  port: 8082

spring:
  application:
    name: player-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: player_db

# Service auth pour validation token
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

# Configuration joueur
player:
  initial-monster-slots: 10
  slots-per-level: 1
  initial-xp-threshold: 50
  xp-multiplier: 1.1
  max-level: 50
