server:
  port: 8084

spring:
  application:
    name: invocation-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: invocation_db

# Service auth pour validation token
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

# Autres services
monster:
  service:
    url: ${MONSTER_SERVICE_URL:http://localhost:8083}
player:
  service:
    url: ${PLAYER_SERVICE_URL:http://localhost:8082}
